<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="fourtek-desktop" name="com.testcase.CreateProjectTest" tests="6" failures="1" timestamp="18 Dec 2017 10:04:35 GMT" time="11.536" errors="0">
  <testcase name="startproject" time="4.112" classname="com.testcase.CreateProjectTest"/>
  <testcase name="typeProjectName" time="0.218" classname="com.testcase.CreateProjectTest"/>
  <testcase name="projectType" time="0.234" classname="com.testcase.CreateProjectTest"/>
  <testcase name="industryType" time="0.235" classname="com.testcase.CreateProjectTest"/>
  <testcase name="targetLanguage" time="0.277" classname="com.testcase.CreateProjectTest"/>
  <testcase name="doClickOnLetsStartButton" time="6.460" classname="com.testcase.CreateProjectTest">
    <failure type="java.lang.AssertionError" message="expected [Project created successfully!] but found [×
Project created successfully!]">
      <![CDATA[java.lang.AssertionError: expected [Project created successfully!] but found [×Project created successfully!]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.testcase.CreateProjectTest.doClickOnLetsStartButton(CreateProjectTest.java:61)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- doClickOnLetsStartButton -->
</testsuite> <!-- com.testcase.CreateProjectTest -->
